version: '3.3'

services:
  nginx: 
    build: ./nginx
    working_dir: /etc/nginx
    volumes:
      - ./nginx/nginx.conf:/nginx.conf
    ports:
      - 80:80
      - 443:443

  react:
    build: ./reacts
    container_name: react
    working_dir: /usr/src/app
    volumes:
      - ./reacts/public:/public
      - ./reacts/src:/src

  flask:
    build: ./flaskService
    container_name: flask
    environment:
      PYTHONUNBUFFERED: 'true'
    volumes: 
      - ./flaskService:/flask
    command: >
      gunicorn -b 0.0.0.0:80 wsgi:app
  
  #dbmysql:
  #  build: ./mysql
  #  container_name: dbflask
  #  working_dir: /var/lib/mysql
  #  volumes:
  #    - ./mysql/data_volume


