version: '3.7'

services:
  nginx: 
    build: ./nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443

  react:
    build: ./reacts
    volumes:
      - ./reacts/public:/usr/src/app/public
      - ./reacts/src:/usr/src/app/src

  flask:
    build: ./flaskService
    working_dir: /flask
    environment: 
      - PYTHONUNBUFFERED=TRUE
      - FLASK_ENV=DEVELOPMENT
    volumes:
      - ./flaskService:/flask
    command: gunicorn -b 0.0.0.0:80 --reload wsgi:app    
  
  #dbmysql:
  #  build: ./mysql
  #  volumes:
  #    - ./mysql/data_volume:/var/lib/mysql
