version: '3.3'

services:
  nginx: 
    build: .
    working_dir: /etc/nginx
    volumes:
      - ./nginx/nginx.conf:/nginx.conf
    ports:
      - 80:80
      - 443:443

  react:
    build: ./reacts
    working_dir: /usr/src/app
    volumes:
      - ./reacts/public:/public
      - ./reacts/src:/src
    command: yarn start
  
  flask:
    build: ./flaskService
    command: >
      gunicorn -b 0.0.0.0:80 wsgi:app
    environment:
      PYTHONUNBUFFERED: 'true'
    volumes: 
      - ./flaskService:/flask
  
  dbmysql:
    build: ./mysql
    volumes:
      - ./mysql/data_volume:/var/lib/mysql

