-- MySQL Script generated by MySQL Workbench
-- sáb 19 oct 2019 15:03:59 CDT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema SinPluma
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema SinPluma
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SinPluma` ;
USE `SinPluma` ;

-- -----------------------------------------------------
-- Table `SinPluma`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SinPluma`.`users` (
  `user_id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(24) NOT NULL,
  `email` VARCHAR(254) NOT NULL,
  `first_name` VARCHAR(60) NOT NULL,
  `last_name` VARCHAR(60) NOT NULL,
  `password_hash` BINARY(64) NOT NULL,
  `user_created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `Username_UNIQUE` (`user_name` ASC) VISIBLE,
  UNIQUE INDEX `EmailAddress_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SinPluma`.`genres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SinPluma`.`genres` (
  `genre_id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`genre_id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SinPluma`.`notebooks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SinPluma`.`notebooks` (
  `notebook_id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT NOT NULL,
  `genre_id` BIGINT NOT NULL,
  `title` VARCHAR(80) NOT NULL,
  `resume` VARCHAR(600) NOT NULL,
  PRIMARY KEY (`notebook_id`),
  INDEX `fk_Notebooks_idx` USING BTREE (`user_id`) VISIBLE,
  INDEX `fk_notebooks_genres1_idx` (`genre_id` ASC) VISIBLE,
  CONSTRAINT `fk_Notebooks`
    FOREIGN KEY (`user_id`)
    REFERENCES `SinPluma`.`users` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_notebooks_genres1`
    FOREIGN KEY (`genre_id`)
    REFERENCES `SinPluma`.`genres` (`genre_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SinPluma`.`pages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SinPluma`.`pages` (
  `page_id` BIGINT NOT NULL AUTO_INCREMENT,
  `notebook_id` BIGINT NOT NULL,
  `position` INT NOT NULL,
  `title` VARCHAR(80) NULL,
  `content` LONGTEXT NULL,
  PRIMARY KEY (`page_id`),
  INDEX `fk_Pages_Notebooks1_idx` (`notebook_id` ASC) VISIBLE,
  CONSTRAINT `fk_Pages_Notebooks`
    FOREIGN KEY (`notebook_id`)
    REFERENCES `SinPluma`.`notebooks` (`notebook_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SinPluma`.`reading`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SinPluma`.`reading` (
  `reading_id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT NOT NULL,
  `notebook_id` BIGINT NOT NULL,
  INDEX `fk_Reading_Users1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_Reading_Notebooks1_idx` (`notebook_id` ASC) VISIBLE,
  PRIMARY KEY (`reading_id`),
  CONSTRAINT `fk_Reading_Users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `SinPluma`.`users` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Reading_Notebooks1`
    FOREIGN KEY (`notebook_id`)
    REFERENCES `SinPluma`.`notebooks` (`notebook_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SinPluma`.`tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SinPluma`.`tags` (
  `tag_id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(90) NOT NULL,
  PRIMARY KEY (`tag_id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SinPluma`.`has_tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SinPluma`.`has_tags` (
  `has_tag_id` BIGINT NOT NULL AUTO_INCREMENT,
  `notebook_id` BIGINT NOT NULL,
  `tag_id` BIGINT NOT NULL,
  INDEX `fk_HasTags_Notebooks1_idx` (`notebook_id` ASC) VISIBLE,
  INDEX `fk_has_tags_tags1_idx` (`tag_id` ASC) VISIBLE,
  PRIMARY KEY (`has_tag_id`),
  CONSTRAINT `fk_HasTags_Notebooks1`
    FOREIGN KEY (`notebook_id`)
    REFERENCES `SinPluma`.`notebooks` (`notebook_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_has_tags_tags1`
    FOREIGN KEY (`tag_id`)
    REFERENCES `SinPluma`.`tags` (`tag_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


LOCK TABLES `genres` WRITE;
/*!40000 ALTER TABLE `genres` DISABLE KEYS */;
INSERT INTO `genres` VALUES (1,'Acción y aventura'),(2,'Antologías'),(3,'Ciencia ficción'),(4,'Cuentos'),(5,'Ensayos'),(6,'Fantasía'),(7,'Ficción'),(8,'Poesía'),(9,'Teatro'),(10,'Terror');
/*!40000 ALTER TABLE `genres` ENABLE KEYS */;
UNLOCK TABLES;