-- MySQL Script generated by MySQL Workbench
-- lun 07 oct 2019 21:14:03 CDT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema SinPluma
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema SinPluma
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SinPluma` ;
USE `SinPluma` ;

-- -----------------------------------------------------
-- Table `SinPluma`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SinPluma`.`Users` (
  `idUser` BIGINT NOT NULL AUTO_INCREMENT,
  `UserName` VARCHAR(24) NOT NULL,
  `EmailAddress` VARCHAR(254) NOT NULL,
  `FirstName` VARCHAR(60) NOT NULL,
  `LastName` VARCHAR(60) NOT NULL,
  `PasswordHash` BINARY(64) NOT NULL,
  `UserCreated` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idUser`),
  UNIQUE INDEX `Username_UNIQUE` (`UserName` ASC) VISIBLE,
  UNIQUE INDEX `EmailAddress_UNIQUE` (`EmailAddress` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SinPluma`.`Notebooks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SinPluma`.`Notebooks` (
  `idNotebook` BIGINT NOT NULL AUTO_INCREMENT,
  `Users_idUsers` BIGINT NOT NULL,
  `Title` VARCHAR(80) NOT NULL,
  `Resume` VARCHAR(600) NOT NULL,
  PRIMARY KEY (`idNotebook`),
  INDEX `fk_Notebooks_idx` USING BTREE (`Users_idUsers`) VISIBLE,
  CONSTRAINT `fk_Notebooks`
    FOREIGN KEY (`Users_idUsers`)
    REFERENCES `SinPluma`.`Users` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SinPluma`.`Pages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SinPluma`.`Pages` (
  `idPage` BIGINT NOT NULL AUTO_INCREMENT,
  `Notebooks_idNotebook` BIGINT NOT NULL,
  `Position` INT NOT NULL,
  `Title` VARCHAR(80) NULL,
  `Content` LONGTEXT NULL,
  PRIMARY KEY (`idPage`),
  INDEX `fk_Pages_Notebooks1_idx` (`Notebooks_idNotebook` ASC) VISIBLE,
  CONSTRAINT `fk_Pages_Notebooks`
    FOREIGN KEY (`Notebooks_idNotebook`)
    REFERENCES `SinPluma`.`Notebooks` (`idNotebook`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SinPluma`.`Genres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SinPluma`.`Genres` (
  `idGenres` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `Notebooks_idNotebook` BIGINT NOT NULL,
  PRIMARY KEY (`idGenres`),
  INDEX `fk_Genres_Notebooks1_idx` (`Notebooks_idNotebook` ASC) VISIBLE,
  CONSTRAINT `fk_Genres_Notebooks1`
    FOREIGN KEY (`Notebooks_idNotebook`)
    REFERENCES `SinPluma`.`Notebooks` (`idNotebook`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SinPluma`.`Reading`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SinPluma`.`Reading` (
  `Users_idUser` BIGINT NOT NULL,
  `Notebooks_idNotebook` BIGINT NOT NULL,
  PRIMARY KEY (`Users_idUser`, `Notebooks_idNotebook`),
  INDEX `fk_Reading_Users1_idx` (`Users_idUser` ASC) VISIBLE,
  INDEX `fk_Reading_Notebooks1_idx` (`Notebooks_idNotebook` ASC) VISIBLE,
  CONSTRAINT `fk_Reading_Users1`
    FOREIGN KEY (`Users_idUser`)
    REFERENCES `SinPluma`.`Users` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reading_Notebooks1`
    FOREIGN KEY (`Notebooks_idNotebook`)
    REFERENCES `SinPluma`.`Notebooks` (`idNotebook`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SinPluma`.`Tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SinPluma`.`Tags` (
  `name` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SinPluma`.`HasTags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SinPluma`.`HasTags` (
  `Notebooks_idNotebook` BIGINT NOT NULL,
  `Tags_name` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`Notebooks_idNotebook`, `Tags_name`),
  INDEX `fk_HasTags_Notebooks1_idx` (`Notebooks_idNotebook` ASC) VISIBLE,
  INDEX `fk_HasTags_Tags1_idx` (`Tags_name` ASC) VISIBLE,
  CONSTRAINT `fk_HasTags_Notebooks1`
    FOREIGN KEY (`Notebooks_idNotebook`)
    REFERENCES `SinPluma`.`Notebooks` (`idNotebook`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_HasTags_Tags1`
    FOREIGN KEY (`Tags_name`)
    REFERENCES `SinPluma`.`Tags` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
